### ISSUE TITLE
gstreamer-mingw install fails on Windows 32 bit

### ISSUE THREAD

**Issue by lebarsfa** [jmcker/ChocolateyPackages#6]
Hello, 

I noticed `choco install gstreamer-mingw` was failing on Windows 32 bit with error message
```
PATH environment variable does not have %GSTREAMER_1_0_ROOT_MINGW_X86_64%\bin in it. Adding...
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: GStreamer gst-launch-1.0.exe could not be found on PATH after install!
```

It seems this can be solved by adding `-eq $true` when checking the variables in the conditions 
https://github.com/jmcker/ChocolateyPackages/blob/4fc857797d91f833253cd67e33b9bd714d49b51d/gstreamer/tools/chocolateyInstall.ps1#L45 
and https://github.com/jmcker/ChocolateyPackages/blob/4fc857797d91f833253cd67e33b9bd714d49b51d/gstreamer/tools/chocolateyBeforeModify.ps1#L19
i.e. 
```powershell
if (${ENV:OS_IS64BIT} -eq $true -And -Not (${ENV:ChocolateyForceX86} -eq $true)) {
```
(`${ENV:OS_IS64BIT} `is set to false on Windows 32 bit, and this value for the variable appears to evaluate to a true condition...)

**Comment by jmcker** [comment]
Indeed that was the case. Thanks for the fix. I pushed it with the latest version.
