### ISSUE TITLE
Plans for GStreamer update to 1.22.4?

### ISSUE THREAD

**Issue by martinslovacek** [jmcker/ChocolateyPackages#7]
This is not exactly an issue, rather a question. In my project we are using GStreamer and are facing an issue which has been fixed in the latest version (1.22.4). We are using your chocolatey package but the latest version is not available yet. 

Do you plan to update the package in a close future? (Our other option would be to fork this repository and create our own package but as matter of fact, we would like to avoid it if possible :-))

**Comment by jmcker** [comment]
Yes. I should have a chance to push new versions this weekend.

**Comment by jmcker** [comment]
1.22.9 through 1.24.2 are pushed. They should clear review shortly.

1.22.4 has been available for some time (https://community.chocolatey.org/packages/gstreamer/1.22.4). I'm assuming you meant 1.24.2 for latest.

**Comment by slovacek-edhouse** [comment]
That's right. Thanks a lot!
