### ISSUE TITLE
The X64 binary of libsndfile is installed in the X86 directory

### ISSUE THREAD

**Issue by asb2m10** [jmcker/ChocolateyPackages#8]
Hello,

I've noticed that if I install libsndfile on a 64-bit machine, the binary will be put in C:\Program Files (x86)\libsndfile even if the 64-bit binary is downloaded.

![image](https://github.com/user-attachments/assets/375a6e15-81a3-4102-ab97-f70b5dc1b8e6)

If I provide the -X86 option, the 32-bit binary will be downloaded, but it will be placed in the C:\Program Files\libsndfile (64-bit) directory. 

Looking at the install script, I think we should remove the `-Not` condition to work correctly.
```
if (${ENV:OS_IS64BIT} -Eq $true -And -Not (${ENV:ChocolateyForceX86} -Eq $true)) {
    $parentFolder = "${ENV:PROGRAMFILES(x86)}"
}
```

**Comment by jmcker** [comment]
Fixed and pushed older releases with a `.20241229` suffix on the versions. Also pushed the `1.2.2` release. Thanks for reporting.
